apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gjs2lcm27-nodejs 
  janus-idp.io/tekton: gjs2lcm27-nodejs
  backstage.io/kubernetes-id: gjs2lcm27-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gjs2lcm27-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  