apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gjs2lcm27-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gjs2lcm27-nodejs 
  name: gjs2lcm27-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gjs2lcm27-nodejs 
